- name: Synchronize nginx global
  synchronize:
    src: files/nginx
    dest: /usr/local
    delete: yes
    recursive: yes
    #owner: yes
    #group: yes
    rsync_opts:
      - "--exclude=sbin"
      - "--exclude=html/*"
      - "--exclude=client_body_temp/*"
      - "--exclude=proxy_temp/*"
      - "--exclude=logs/*.pid"
      - "--exclude=logs/*.log"
      - "--exclude=logs/others/*"
      - "--exclude=logs/rzcf.com/*"
      - "--exclude=logs/ylww.com/*"
      - "--exclude=logs/vyiot.com/*"
      - "--exclude=logs/zmyiot.com/*"
  notify:
    - reload nginx
    - random delay

