---
- hosts: local
  gather_facts: True
  #remote_user: root
  #become: True
  #become_user: root
  #become_method: sudo
  vars:
    mysql_version: 8.0.25
    #mysql_version: 5.7.33
  roles:
    - mysql




