



---
- name: Deploy Highly Available NTP with LVS-DR
  hosts: ntp
  gather_facts: True
  vars:
    priority: 100
    virtual_ip: 172.16.51.100
    virtual_port: 123
  roles:
    - ntpServ
    - keepalived
    - lvs
    
  pre_tasks:
  - name: Check if firewalld is running
    systemd:
      name: firewalld
    register: firewalld_status
