



---
- name: Deploy Highly Available NTP with LVS-DR
  hosts: ntp
  gather_facts: True
  vars:
    vip_address: 172.16.51.100
    interface: eth0
    loopback_interface: lo
    keepalived_router_id: 51
    keepalived_auth_pass: 12345678
  roles:
    - ntpServ
      #when: "'rs' in group_names"
    - keepalived
      #when: "'ds' in group_names"
    - lvs
    
  pre_tasks:
  - name: Check if firewalld is running
    systemd:
      name: firewalld
    register: firewalld_status
