---
- name: create dir 
  file:
    path: "{{ confd_base_home }}/{{ item }}"
    state: directory
    recurse: yes
    owner: root
    group: root
  with_items:
    - bin
    - conf.d
    - templates
- name: Download binary file
  get_url:
    url: "{{ download_url }}/{{ confd_binary_file }}"
    dest: "{{ confd_base_home }}/bin/confd"
    mode: 755

- name: sync configurate
  template:
    src: "{{ item.tmpl }}"
    dest: "{{ confd_base_home }}/{{ item.path }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - { tmpl: target.tmpl.j2, path: templates/target.tmpl}
    - { tmpl: target.toml.j2, path: conf.d/target.toml}
