# Timeout (tcp tcpfin udp): 900 120 300
- name: Create systemd unit file for VIP setup
  copy:
    dest: /usr/lib/systemd/system/ipvs-timeout.service
    content: |
      [Unit]
      Description=Set IPVS UDP timeout
      After=network.target

      [Service]
      Type=oneshot
      ExecStart=/usr/sbin/ipvsadm --set 900 120 10

      [Install]
      WantedBy=multi-user.target
    mode: 0644
    force: true
  notify: Add time options for lvs
