---
- name: Create systemd unit file for VIP setup
  copy:
    dest: /usr/lib/systemd/system/add-vip.service
    content: |
      [Unit]
      Description=Add LVS VIP to loopback interface
      After=network.target

      [Service]
      Type=oneshot
      ExecStart=/sbin/ip addr add {{ virtual_ip }}/32 dev lo
      ExecStop=/sbin/ip addr del {{ virtual_ip }}/32 dev lo
      RemainAfterExit=true

      [Install]
      WantedBy=multi-user.target
    mode: 0644
    force: true
  notify: Add vip for read server

- name: Disable ARP on VIP
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_file: /etc/sysctl.d/rs.conf
    reload: yes
  loop:
    - {key: "net.ipv4.conf.all.arp_ignore", value: 1}
    - {key: "net.ipv4.conf.all.arp_announce", value: 2}
    - {key: "net.ipv4.conf.lo.arp_ignore", value: 1}
    - {key: "net.ipv4.conf.lo.arp_announce", value: 2}

- name: Allow NTP port if firewalld is running
  firewalld:
    port: 123/udp
    permanent: yes
    state: enabled
    immediate: yes
  when: firewalld_status.status.ActiveState == "active"
