---
- name: Add vip for read server
  systemd:
    name: add-vip
    enabled: true
    state: restarted
    daemon_reload: yes

- name: Add time options for lvs
  systemd:
    name: ipvs-timeout
    enabled: true
    state: restarted
    daemon_reload: yes
