#- name: Set keepalived priority from IP last octet
  #set_fact:
    #priority: "{{ (ansible_default_ipv4.address.split('.')[-1] | int) }}"
  #when:
     #- ( ansible_default_ipv4.address.split('.')[-1] == '22'  )
