---
- name: make sure chronyd is installed
  package:
    name: chrony
    state: present
    #update_cache: yes
  notify:
    - restart chrony service

- name: rsync chrony configuration
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    #backup: yes
  notify:
    - restart chrony service

