---
- sysctl:
    name: vm.swappiness
    value: 5
#    state: present
#    reload: yes
#    sysctl_file: /etc/sysctl.conf
#    sysctl_set: yes
- sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
- sysctl:
    name: net.ipv4.tcp_tw_recycle
    value: 1
- sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 30
- sysctl:
    name: net.ipv4.ip_local_port_range
    value: 1024 65000
- pam_limits:
    domain: '*'
    limit_type: '-'
    limit_item: nofile
    value: 64000








