---
- name: adjust kernel options
  sysctl:
    name: '{{ item.option }}'
    value: '{{ item.value }}'
    reload: yes
  loop:
    - {option: "vm.swappiness", value: 5}
    - {option: "net.ipv4.tcp_tw_reuse", value: 1}
    - {option: "net.ipv4.tcp_tw_recycle", value: 1}
    - {option: "net.ipv4.tcp_fin_timeout", value: 30}
    - {option: "net.core.somaxconn", value: 1024}
    - {option: "net.ipv4.tcp_max_syn_backlog", value: 20480}
    - {option: "net.ipv4.ip_local_port_range", value: 1024 65000}
    #- {option: "net.netfilter.nf_conntrack_max", value: 12262144}
- name: adjust number of open files
  pam_limits:
    domain: '*'
    limit_type: '-'
    limit_item: nofile
    value: '64000'
#
