---
- name: mkdir {{ base_dir }}
  file:
    path: "{{ base_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
- name: unarchive "{{ mysql_archive }}"
  unarchive:
    src: "{{ download_url }}/{{ mysql_archive }}"
    dest: "{{ base_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
- name: Fix ownershipper
  file:
    path: "{{ base_dir }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: yes
- name: Copy Config File
  template:
    src: my.cnf
    dest: "{{ config_file }}"
- name: Copy Daemon File
  template: 
    src: mysql.server
    dest: "{{ daemon_file }}"
    mode: a+x
- name: Init mysql Instance
  shell: "{{ base_dir }}/bin/mysqld --initialize-insecure --user={{ user }} --basedir={{ base_dir }} --datadir={{ data_dir }}"
- name: start on boot
  service:
    name: "{{ daemon }}"
    state: started
    enabled: yes











