---
- include: vars.yaml
- name: Add user for mysql daemon
  user:
    name: mysql
    shell: /usr/sbin/nologin
    create_home: False
- name: mkdir {{ base_dir }}
  file:
    path: "{{ base_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
- name: unarchive "{{ mysql_archive }}"
  unarchive:
    src: "{{ download_url }}/{{ mysql_archive }}"
    dest: "{{ base_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
- name: Fix ownershipper
  file:
    path: "{{ base_dir }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: yes
- name: Copy Config File
  template:
    src: "{{ mysql_version[0:3] }}/my.cnf"
    dest: "{{ config_file }}"
- name: Copy Daemon File
  copy:
    src: "{{ base_dir }}/support-files/mysql.server"
    dest: "{{ daemon_file }}"
    remote_src: yes
    mode: a+x
  #template: 
  #  src: mysql.server
  #  dest: "{{ daemon_file }}"
  #  mode: a+x

- name: Init mysql Instance
  shell: "{{ base_dir }}/bin/mysqld --initialize-insecure --user={{ user }} --basedir={{ base_dir }} --datadir={{ data_dir }}"
- name: start on boot
  service:
    name: "{{ daemon }}"
    state: started
    enabled: yes

- name: import python modules
  include: pys.yaml
- name: Create Remote User
  no_log: true
  mysql_user:
    name: root
    password: "{{ item.p }}"
    host: "{{ item.h }}"
    login_unix_socket: '/usr/local/mysql/mysql.sock'
    priv: '*.*:ALL,GRANT'
    state: present
  loop:
    - { h: '%', p: mysqlpass }
    - { h: localhost, p: mysqlpass }











