---
- name: Install keepalived
  #ansible.builtin.package:
  package:
    name: keepalived
    state: present
  notify: Restart keepalived

- name: Configure keepalived for LVS-DR
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
    setype: etc_t
  notify: Restart keepalived
