---
- name: install chrony
  yum:
    name: chrony
    state: present
    #disablerepo: '*'
    #enablerepo: 'local'
  notify:
    - restart chrony service
- name: sync chrony configuration
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart chrony service

- name: Kernel Performance
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_file: /etc/sysctl.d/chrony.conf
    reload: yes
  loop:
    - {key: "net.core.rmex_max", value: 26214400}
    - {key: "net.core.netdev_max_backlog", value: 5000}
