---
- include_vars: waf.yaml
  when: isWaf
- include_vars: general.yaml
  when: not isWaf
- name: install chrony
  yum:
    name: chrony
    state: present
    disablerepo: '*'
    enablerepo: 'local'
  notify:
    - start daemon
- name: sync configuration
  template:
    src: chrony.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - start daemon
- name: config daemon args
  lineinfile:
    path: /etc/sysconfig/chronyd
    regexp: '^OPTIONS='
    line: 'OPTIONS="-4"'
  notify:
    - start daemon

