---
- include_vars: vars.yaml
- name: Collect facts
  set_fact:
    postfix: linux-glibc2.12-x86_64.tar.gz
  when:
     - mysql_version[0:3] == '5.7'
- name: Collect facts
  set_fact:
    postfix: linux-glibc2.12-x86_64.tar.xz
  when:
     - ( mysql_version[0:3] == '8.0' )
- name: debug
  debug:
     msg: "{{ mysql_archive }}"
     
