---
- name: mkdir
  file:
    path: "{{ java_home }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
- name: unarchive
  unarchive:
    src: "{{ download_url }}/{{ jdk_archive }}"
    dest: "{{ java_home }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: "{{ user }}"
    group: "{{ group }}"
- name: set Java_home
  lineinfile:
    path: "{{ profile }}"
    regexp: JAVA_HOME=
    line:  export JAVA_HOME={{ java_home }}
    state: present
- name: set Java_Path
  lineinfile:
    path: "{{ profile }}"
    line: export PATH=$JAVA_HOME/bin:$PATH



