- name: Install EPEL
  template:
    src: "{{ item }}"
    dest: present
    owner: root
    group: root
  #when: ansible_distribution == "CentOS" and ansible_distribution_version|int >= 8
  when: 
    - ansible_os_family in ["CentOS","RedHat"]
    - ansible_distribution_version|int >= 8
  with_fileglob:
    - templates/epel*
- name: Install EPEL
  package:
    name: epel-release
    state: present
  when: 
    - ansible_os_family in ["CentOS","RedHat"]
    - ansible_distribution_version|int <= 7

- name: Install python2-dnf for Fedora dnf support
  raw: dnf install -y python2-dnf
  when:
    - ansible_distribution == "Fedora"
    - ansible_python.version.major == 2
  register: fedora_dnf
  changed_when: '"Nothing to do." not in fedora_dnf.stdout'

- name: Install openvpn
  package:
   name: "{{ item }}"
   state: present
  with_items:
    - openvpn
    - openssl

- name: Install LDAP plugin
  package:
   name: openvpn-auth-ldap
   state: present
  when: openvpn_use_ldap

# RHEL has the group 'nobody', 'Debian/Ubuntu' have 'nogroup'
# standardize on 'nogroup'
- name: Ensure group 'nogroup' is present
  group:
    name: nogroup
    state: present
    system: yes
